Nombre = input("Cual es tu nombre? ")
Apellido = input("Cual es tu apellido? ")
Carrera = input("Que carrera estudias? ")
Asignatura = input("Que asignatura es esta? ")
Sede = input("En que sede de Inacap estas? ")
Semestre = input("Que semestre cursas? ")
Año = input("En que año estamos? ")
Ciudad = input("Desde que ciudad estas haciendo esto?")
Edad = input("Que edad tienes? ")
print( Nombre, Apellido, Carrera, Asignatura, Sede, Semestre, Año, Ciudad, Edad)
